### ISSUE TITLE
Freezes settings

### ISSUE THREAD

**Issue by Psychokiller1888** [OllisGit/OctoPrint-PauseAt#1]
Hi!

On octoprint 1.3.9 adding this plugin makes the settings not open anymore

**Comment by OllisGit** [comment]
Hi @Psychokiller1888 ,
I am back from a long vacation and now I can support you with your issue.

Thx, for the Info! 
But this Plugin has no released version. It's still work in progress.
And sorry to say, but I have no schedule when the first release will be done.

BR
Olli
