### ISSUE TITLE
status

### ISSUE THREAD

**Issue by tcurdt** [OllisGit/OctoPrint-PauseAt#2]
I don't seem to find any code that does actual work. Only settings.
Is this an abandoned work in progress?

**Comment by OllisGit** [comment]
Hi @tcurdt 
I am back from a long vacation and now I can support you with your issue.

This Plugin has no released version. It's still work in progress.
And sorry to say, but I have no schedule when the first release will be done.

BR
Olli

**Comment by tcurdt** [comment]
I found another plugin that does the job. So no worries.

**Comment by cosminr86** [comment]
Can you share?

**Comment by tcurdt** [comment]
https://plugins.octoprint.org/plugins/multi_colors/
